apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace_id: "09e77b80-98fd-4d77-a42f-48bf706d9d8b"
  name: deviceshifu-cam-01-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: HTTP IP Camera Device
    driverImage:
  instructions: |
    instructions:
      "move/down":
      "move/left":
      "move/right":
      "capture":
      "info":
      "stream":
      "move/up":
  telemetries: |
    telemetries:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace_id: "09e77b80-98fd-4d77-a42f-48bf706d9d8b"
  name: deviceshifu-cam-01-service
  namespace: deviceshifu
spec:
  ports:
  - name: http-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-cam-01-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace_id: "09e77b80-98fd-4d77-a42f-48bf706d9d8b"
  name: deviceshifu-cam-01-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-cam-01-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-cam-01-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.64.0-rc1
          name: deviceshifu-http
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-cam-01-configmap
              mountPath: /etc/edgedevice/config
              readOnly: true
          env:
          - name: EDGEDEVICE_NAME
            value: "deviceshifu-cam-01-edgedevice"
          - name: EDGEDEVICE_NAMESPACE
            value: "devices"
        - name: camera-python
          image: edgehub/camera-python:v0.0.3
          ports:
            - containerPort: 11112
              protocol: TCP
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-cam-01"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: IP_CAMERA_ADDRESS
              value: "bj-hikcamera-01.saifai.cn"
            - name: IP_CAMERA_RTSP_PORT
              value: "40554"
            - name: IP_CAMERA_HTTP_PORT
              value: "40080"
            - name: IP_CAMERA_CONTAINER_PORT
              value: "11112"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: IP_CAMERA_USERNAME
              value: "guest"
            - name: IP_CAMERA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cam-01-secret
                  key: IP_CAMERA_PASSWORD
                  optional: false
      volumes:
        - name: deviceshifu-cam-01-configmap
          configMap:
            name: deviceshifu-cam-01-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  labels:
    app: deviceshifu-cam-01
    workspace_id: "09e77b80-98fd-4d77-a42f-48bf706d9d8b"
  name: deviceshifu-cam-01-edgedevice
  namespace: devices
spec:
  sku: "HTTP IP Camera Device"
  connection: "Ethernet"
  address: "0.0.0.0:11112"
  protocol: "HTTP"
---
apiVersion: v1
kind: Secret
metadata:
  name: cam-01-secret
  namespace: deviceshifu
type: Opaque
data:
  IP_CAMERA_PASSWORD: SGVsbG9TaGlmdQ==